name: Detect new apps and trigger cross-repo scripts

on:
  pull_request:
    types: [opened, reopened]
    paths:
      - "config/apps.yaml"

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  handle-new-apps:
    runs-on: ubuntu-latest
    env:
      DEPLOY_REPO: ${{ github.repository }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      PR_HEAD_REF: ${{ github.head_ref }}
      PR_BASE_REF: ${{ github.base_ref }}
      GITHUB_ACTOR: ${{ github.actor }}
    steps:
      - name: Checkout PR branch (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Configure Git for deploy repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Utkarshsaini01/test-pulumi.git

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
          pip install pyjwt cryptography

      - name: Run new app handle script
        env:
          APP_ID: ${{ secrets.GH_APP_ID }}
          INSTALLATION_ID: ${{ secrets.APP_INSTALLATION_ID }}
          APP_KEY: ${{ secrets.GH_APP_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # default token for actions (same repo operations)
          INFRA_REPO_SSH: "git@github.com:Utkarshsaini01/test_1.git"  # change to actual repo
          ADDONS_REPO_SSH: "git@github.com:Utkarshsaini01/addons.git"    # change to actual repo
          INFRA_REPO: "Utkarshsaini01/test-cd-1"
          ADDONS_REPO: "Utkarshsaini01/addons"
        run: |
          # run the Python automation script that compares base and head and does everything
          python scripts/handle_new_apps.py \
            --base-branch ${PR_BASE_REF} \
            --head-branch ${PR_HEAD_REF} \
            --deploy-repo $DEPLOY_REPO \
            --infra-repo $INFRA_REPO \
            --addons-repo $ADDONS_REPO

      - name: No-op if no changes
        if: steps.check_changed.outputs.changed == 'false'
        run: echo "config/apps.yaml not changed — nothing to do."
